### ISSUE TITLE
Defaults to very old Angular version

### ISSUE THREAD

**Issue by steveblue** [DeMoorJasper/Angular-Parcel-Boilerplate#2]
This is based off a very old version of Angular. If you are intending to provide an example of how to use parcel with Angular, you should be using @angular packages ^5.0.0. There is a lot missing to this example as well. Angular apps are compiled AOT using the AOT Compiler (`ngc`) which is a wrapper for TypeScript.

**Comment by DeMoorJasper** [comment]
I just noticed this today as well, kinda got puzzled by the docs though but i'll look into it one time

**Comment by steveblue** [comment]
ATM I am a bit puzzled how Angular can be integrated with Parcel. The source needs to be AOT Compiled before it is bundled, each module in the source should be code split if it is lazyloaded.

The only way to compile an Angular app is with `ngc`, a wrapper around `tsc`. `ngc` takes a config with an Array of files to compile (in tsconfig.json). It can be set in watch mode and output AOT compiled code in a directory.

Ideally, Parcel would be able to take the AOT compiled code and code split the output on the fly if the user has an lazyloaded modules. 

Typically, an Angular App has a file named `main.ts` for bootstrapping an Angular app.

```
import { platformBrowser } from '@angular/platform-browser';
import { AppModule } from './src/app/app.module';

platformBrowser().bootstrapModule(AppModule)
    .catch(err => console.error(err));
```

AppModule sits at the top of the tree. An Angular app can have lazyloaded Module that need to be code split and bundled. How does someone provide the AST of Angular Modules to Parcel so it knows how to code split the app?

**Comment by steveblue** [comment]
@DeMoorJasper checkout parcel-plugin-typescript develop branch, latest commit has support for JIT

**Comment by DeMoorJasper** [comment]
Thanks, i'll update and refactor this example once the release of those changes land

**Comment by DeMoorJasper** [comment]
@steveblue This should now be fixed
