### ISSUE TITLE
issue created in parcel-examples to include this repo or at least link to it

### ISSUE THREAD

**Issue by ghost** [DeMoorJasper/Angular-Parcel-Boilerplate#3]
Hey, thanks again for creating this nice example. I created an issue on the parcel-examples repo so that it can be linked to or incorporated into that repo: https://github.com/parcel-bundler/examples/issues/3

(Note: I'm not a dev on parcel, just a fan of angular and any build system that competes with webpack)

**Comment by DeMoorJasper** [comment]
Yeah i'll upload it to examples once i figure out how to get the final version of angular to work with parcel, probably just gonna wait on the advanced typescript plugin to get a bit further in development

**Comment by ghost** [comment]
awesome, it looks like that [repo is for actual code samples that use parcel](https://github.com/parcel-bundler/examples) so you would just need to open up a PR whenever you're ready on that repo.

again, awesome work on this, can't wait to use it as a base for my own projects 💯
