### ISSUE TITLE
Request: Support scss and HMR and production build

### ISSUE THREAD

**Issue by HackPoint** [DeMoorJasper/Angular-Parcel-Boilerplate#4]

**Comment by DeMoorJasper** [comment]
Production builds should work using `yarn build` or `npm run build`
HMR should work using the start command
scss is supported by Parcel and should be supported in this boilerplate as a result

**Comment by HackPoint** [comment]
@DeMoorJasper Thanks. Does it compatible with ng-cli?

**Comment by DeMoorJasper** [comment]
I have not tested out any compatibility with ng cli, but i guess most features should work.
Let me know if you've tested it
