### ISSUE TITLE
App does not work

### ISSUE THREAD

**Issue by bellizio** [DeMoorJasper/Angular-Parcel-Boilerplate#5]
1. clone the repo
2. run `npm install`
3. run `npm start`

The following error occurs:

`
(node:17033) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: ENOENT: no such file or directory, open '/Users/dbellizio/Dev/angular/Angular-Parcel-Boilerplate/node_modules/parcel-bundler/src/builtins/prelude.min.js'
(node:17033) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by DeMoorJasper** [comment]
fixed in 07f8b4f1db32fcbb06f0b6bf8452b39afe718721
